name: plan_it_on
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  shared_preferences: ^0.5.7+3
  cloud_firestore: ^0.13.6
  otp_text_field: ^1.0.1
  random_string: ^2.0.1
  image_picker: ^0.6.7+1
  firebase_storage: ^3.1.6
  flutter_datetime_picker: ^1.3.8
  intl: ^0.16.1
  flutter_spinkit: ^4.1.2+1
  confetti: ^0.5.2
  flutter_share: ^1.0.2+1
  bottom_navy_bar: ^5.4.0
  qr_flutter: ^3.2.0
  social_media_buttons: ^0.1.2
  flutter_show_more: ^0.1.2
  flutter_barcode_scanner: ^1.0.1
  lottie: ^0.4.0+1
  place_picker: ^0.9.14
  geoflutterfire: ^2.1.0
  geolocator: ^5.3.2+2
  fluttertoast: ^4.0.1 
  flushbar: ^1.10.4
  google_maps_place_picker: ^0.9.5
  latlong: ^0.6.1
  razorpay_flutter: ^1.2.1
  timeago: ^2.0.26
  flutter_linkify: ^3.1.3
  url_launcher: ^5.5.0
  international_phone_input: ^1.0.4
  flutter_fluid_slider: ^1.0.2
  auto_size_text: ^2.1.0
  flutter_html: ^1.0.2
  fancy_drawer: ^1.0.0
  flutter_icons: ^1.1.0
  firebase_messaging: ^6.0.16
  clipboard: ^0.1.2+8
  intro_slider: ^2.3.2
  wiredash: ^0.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_config: ^1.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
dependency_overrides:
  flutter_chips_input: ^1.9.0-dev.1
  flutter_svg: ^0.18.0
  
flutter:
  
  assets:
    - assets/

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
